project_id = "yrowmukralyijublgkuk"

[functions.create-ipaymu-payment]
verify_jwt = true

[functions.ipaymu-webhook]
verify_jwt = false

[functions.create-paypal-payment]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.update-commissions]
verify_jwt = false
