import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.products': 'Products',
    'nav.admin': 'Admin',
    'nav.messages': 'Messages',
    'nav.login': 'Login',
    'nav.startSelling': 'Start Selling',
    'nav.dashboard': 'Dashboard',
    'nav.sellerDashboard': 'Seller Dashboard',
    'nav.buyerDashboard': 'Buyer Dashboard',
    'nav.signOut': 'Sign Out',
    'nav.blog': 'Blog',
    
    // Hero Section
    'hero.badge': 'Global Digital Marketplace',
    'hero.title': 'Buy & Sell Digital Products With Ease',
    'hero.subtitle': 'Global platform for creators to sell e-books, designs, music, software, templates, and much more.',
    'hero.startSelling': 'Start Selling Now',
    'hero.viewProducts': 'View Products',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Start selling in 4 easy steps',
    'howItWorks.step1.title': 'Create Account',
    'howItWorks.step1.desc': 'Sign up free',
    'howItWorks.step2.title': 'Upload Product',
    'howItWorks.step2.desc': 'Add file or link',
    'howItWorks.step3.title': 'Receive Payment',
    'howItWorks.step3.desc': 'Secure payment',
    'howItWorks.step4.title': 'Buyer Downloads',
    'howItWorks.step4.desc': 'Instant access',
    
    // Advantages
    'advantages.title': 'Digisellix Advantages',
    'advantages.subtitle': 'Trusted marketplace for creators',
    'advantages.payments.title': 'Fast Payments',
    'advantages.payments.desc': 'Secure global payments',
    'advantages.global.title': 'Global Sellers',
    'advantages.global.desc': 'Worldwide reach',
    'advantages.upload.title': 'Flexible Upload',
    'advantages.upload.desc': 'File or link',
    'advantages.platform.title': 'Modern Platform',
    'advantages.platform.desc': 'User-friendly',
    
    // Product Sections
    'featured.badge': 'Featured Products',
    'featured.title': 'Premium Picks',
    'featured.subtitle': 'Handpicked premium products from top creators',
    'popular.badge': 'Best Sellers',
    'popular.title': 'Popular Products',
    'popular.subtitle': 'Most purchased products by our community',
    'popularSellers.badge': 'Top Sellers This Month',
    'popularSellers.title': 'Popular Sellers',
    'popularSellers.subtitle': 'Top performing sellers with the most sales this month',
    'popularSellers.noDescription': 'Quality digital products seller',
    'popularSellers.sales': 'sales',
    'popularSellers.products': 'products',
    'popularSellers.viewStore': 'View Store',
    'newest.badge': 'Just Added',
    'newest.title': 'Newest Products',
    'newest.subtitle': 'Fresh products just added to the marketplace',
    'reviews.badge': 'Customer Reviews',
    'reviews.title': 'What Buyers Say',
    'reviews.subtitle': 'Recent reviews from our satisfied customers',
    'reviews.noComment': 'Great product!',
    'explore.title': 'Explore All Products',
    'explore.subtitle': 'Browse our complete collection of digital products',
    'explore.viewAll': 'View All Products',
    
    // CTA
    'cta.title': 'Ready to Start Your Digital Business?',
    'cta.subtitle': 'Join thousands of creators who trust Digisellix',
    'cta.button': 'Start Free Now',
    
    // Footer
    'footer.tagline': 'Global marketplace for digital products',
    'footer.product': 'Product',
    'footer.browseProducts': 'Browse Products',
    'footer.sellProducts': 'Sell Products',
    'footer.company': 'Company',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.contactAdmin': 'Contact Admin',
    'footer.legal': 'Legal',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
    'footer.copyright': '© 2024 Digisellix. All rights reserved.',
    'footer.notification': 'Welcome to Digisellix - Your trusted digital marketplace!',
    'footer.notificationSales': 'New products added daily',
    'footer.notificationTrust': 'Secure payments & instant downloads',
    
    // Products Page
    'products.title': 'Discover Products',
    'products.subtitle': 'Find the perfect digital product for your needs',
    'products.allCategories': 'All Categories',
    'products.searchPlaceholder': 'Search products...',
    'products.priceRange': 'Price Range',
    'products.noProducts': 'No products found',
    'products.tryAdjusting': 'Try adjusting your search or filter criteria',
    'products.previous': 'Previous',
    'products.next': 'Next',
    
    // Product Card
    'product.viewDetails': 'View Details',
    'product.topRated': 'Top',
    'product.reviews': 'reviews',
    
    // Wishlist
    'wishlist.title': 'My Wishlist',
    'wishlist.subtitle': 'Products you saved for later',
    'wishlist.empty': 'Your wishlist is empty',
    'wishlist.emptyDesc': 'Start adding products you love to your wishlist',
    'wishlist.browseProducts': 'Browse Products',
    'nav.wishlist': 'Wishlist',
    
    // Blog
    'blog.title': 'Digisellix Blog',
    'blog.subtitle': 'Tips, guides, and resources for digital creators and sellers',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have questions? We\'re here to help. Reach out to our team.',
    'contact.emailTitle': 'Email',
    'contact.chatTitle': 'Live Chat',
    'contact.chatDesc': 'Chat with our support team via WhatsApp',
    'contact.hoursTitle': 'Business Hours',
    'contact.hoursDesc': 'Monday - Friday, 9AM - 6PM (WIB)',
    'contact.locationTitle': 'Location',
    'contact.locationDesc': 'Jakarta, Indonesia',
    'contact.formTitle': 'Send us a Message',
    'contact.formDesc': 'Fill out the form below and we\'ll get back to you as soon as possible.',
    'contact.nameLabel': 'Name',
    'contact.namePlaceholder': 'Your name',
    'contact.emailLabel': 'Email',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.subjectLabel': 'Subject',
    'contact.subjectPlaceholder': 'What is this about?',
    'contact.messageLabel': 'Message',
    'contact.messagePlaceholder': 'Tell us how we can help you...',
    'contact.sendButton': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.successTitle': 'Message Sent!',
    'contact.successMessage': 'Thank you for reaching out. We\'ll get back to you soon.',
    'contact.errorTitle': 'Error',
    'contact.errorMessage': 'Failed to send message. Please try again.',
    
    // Language Switcher
    'language.english': 'English',
    'language.indonesian': 'Indonesia',

    // Auth Page
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.welcomeBack': 'Welcome Back',
    'auth.enterCredentials': 'Enter your credentials to access your account',
    'auth.createAccount': 'Create Account',
    'auth.startSelling': 'Start selling your digital products today',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.loading': 'Loading...',
    'auth.iWantTo': 'I want to',
    'auth.buyProducts': 'Buy Products',
    'auth.buyProductsDesc': 'Purchase and download digital products',
    'auth.sellProducts': 'Sell Products',
    'auth.sellProductsDesc': 'Upload and sell your digital products',
    'auth.selectBoth': 'You can select both options to buy and sell',
    'auth.orContinueWith': 'Or continue with',
    'auth.googleLoginFailed': 'Google login failed',
    'auth.redirectingToGoogle': 'Redirecting to Google...',
    'auth.backToHome': '← Back to Home',

    // Product Detail Page
    'productDetail.backToProducts': 'Back to Products',
    'productDetail.by': 'By',
    'productDetail.sales': 'sales',
    'productDetail.securePurchase': 'Secure Purchase',
    'productDetail.instantAccess': 'Instant access after payment. All files are scanned and verified.',
    'productDetail.buyNow': 'Buy Now',
    'productDetail.chatWithSeller': 'Chat with Seller',
    'productDetail.starting': 'Starting...',
    'productDetail.description': 'Description',
    'productDetail.productDetails': 'Product Details',
    'productDetail.category': 'Category',
    'productDetail.totalSales': 'Total Sales',
    'productDetail.listedOn': 'Listed on',
    'productDetail.relatedProducts': 'Related Products',
    'productDetail.notFound': 'Product not found',
    'productDetail.notFoundDesc': "The product you're looking for doesn't exist or has been removed.",
    'productDetail.pleaseSignIn': 'Please sign in to purchase',
    'productDetail.cannotBuyOwn': 'You cannot buy your own product',
    'productDetail.orderCreated': 'Order created! Redirecting to checkout...',
    'productDetail.pleaseSignInChat': 'Please sign in to chat with seller',
    'productDetail.ownProduct': 'This is your own product',
    'productDetail.faq': 'Frequently Asked Questions',

    // Share
    'share.title': 'Share',
    'share.shareVia': 'Share via',
    'share.copyLink': 'Copy link',
    'share.copied': 'Copied!',
    'share.linkCopied': 'Link copied to clipboard',
    'share.copyFailed': 'Failed to copy link',
    'share.more': 'More options',

    // Forum
    'nav.forum': 'Forum',
    'forum.title': 'Community Forum',
    'forum.subtitle': 'Discuss with the community',
    'forum.newTopic': 'New Topic',
    'forum.comments': 'comments',
    'forum.noTopics': 'No topics yet',
    'forum.beFirst': 'Be the first to start a discussion!',
    'forum.createTopic': 'Create Topic',
    'forum.signInToPost': 'Sign in to post',
    'forum.joinDiscussion': 'Want to join the discussion?',
    'forum.backToForum': 'Back to Forum',
    'forum.topicNotFound': 'Topic not found',
    'forum.noComments': 'No comments yet. Be the first to comment!',
    'forum.writeComment': 'Write a comment...',
    'forum.postComment': 'Post Comment',
    'forum.posting': 'Posting...',
    'forum.commentAdded': 'Comment added!',
    'forum.commentError': 'Failed to add comment',
    'forum.commentDeleted': 'Comment deleted',
    'forum.signInToComment': 'Sign in to comment',
    'forum.createNewTopic': 'Create New Topic',
    'forum.moderationNotice': 'Your topic will be reviewed by our team before being published.',
    'forum.topicTitle': 'Topic Title',
    'forum.titlePlaceholder': 'Enter a descriptive title...',
    'forum.topicContent': 'Content',
    'forum.contentPlaceholder': 'Share your thoughts, questions, or ideas...',
    'forum.cancel': 'Cancel',
    'forum.submitTopic': 'Submit Topic',
    'forum.submitting': 'Submitting...',
    'forum.topicSubmitted': 'Topic submitted for review!',
    'forum.submitError': 'Failed to submit topic',
    'forum.fillAllFields': 'Please fill in all fields',
    'forum.signInRequired': 'Sign in required',
    'forum.signInToCreateTopic': 'Please sign in to create a new topic.',
    'forum.pendingReview': 'Pending Review',
    'forum.allTopics': 'All Topics',
    'forum.approved': 'Approved',
    'forum.rejected': 'Rejected',
    'forum.pending': 'Pending',
    'forum.topicApproved': 'Topic approved!',
    'forum.topicRejected': 'Topic rejected',
    'forum.topicDeleted': 'Topic deleted',
    'forum.updateError': 'Failed to update topic',
    'forum.confirmDelete': 'Delete Topic?',
    'forum.deleteWarning': 'This action cannot be undone. The topic and all its comments will be permanently deleted.',
    'forum.delete': 'Delete',
    'forum.noPendingTopics': 'No topics pending review',
    'forum.noTopicsYet': 'No topics created yet',

    // Checkout Page
    'checkout.title': 'Checkout',
    'checkout.back': 'Back',
    'checkout.orderSummary': 'Order Summary',
    'checkout.customOrder': 'Custom Order',
    'checkout.digitalProduct': 'Digital Product',
    'checkout.priceUSD': 'Price (USD)',
    'checkout.priceIDR': 'Price (IDR)',
    'checkout.total': 'Total',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.securePayment': 'Secure payment processing powered by PayPal',
    'checkout.paypalOptions': 'PayPal Payment Options:',
    'checkout.paypalBalance': 'PayPal Balance',
    'checkout.creditDebit': 'Credit/Debit Cards (Visa, Mastercard, Amex)',
    'checkout.bankAccounts': 'Bank Accounts (linked to PayPal)',
    'checkout.continuePaypal': 'Continue with PayPal',
    'checkout.secureInfo': 'Your payment information is encrypted and secure. You will get instant access to your purchase after payment is confirmed.',
    'checkout.orderNotFound': 'Order not found',
    'checkout.browseProducts': 'Browse Products',
    'checkout.creatingPayment': 'Creating payment...',
    'checkout.redirectingPaypal': 'Redirecting to PayPal...',
    'checkout.pleaseSignIn': 'Please sign in to continue',

    // Payment Success Page
    'paymentSuccess.backToDashboard': 'Back to Dashboard',
    'paymentSuccess.paymentSuccessful': 'Payment Successful!',
    'paymentSuccess.orderConfirmed': 'Your order has been confirmed and is ready for download.',
    'paymentSuccess.paid': 'Paid',
    'paymentSuccess.paymentPending': 'Payment Pending',
    'paymentSuccess.waitingConfirmation': "We're waiting for payment confirmation. This page will update automatically.",
    'paymentSuccess.pending': 'Pending',
    'paymentSuccess.paymentFailed': 'Payment Failed',
    'paymentSuccess.couldNotProcess': 'Your payment could not be processed. Please try again.',
    'paymentSuccess.failed': 'Failed',
    'paymentSuccess.orderDetails': 'Order Details',
    'paymentSuccess.orderId': 'Order ID',
    'paymentSuccess.paymentMethod': 'Payment Method',
    'paymentSuccess.amount': 'Amount',
    'paymentSuccess.paidAt': 'Paid At',
    'paymentSuccess.downloadProduct': 'Download Your Product',
    'paymentSuccess.purchaseReady': 'Your purchase is ready! Click the button below to download your digital product.',
    'paymentSuccess.downloadNow': 'Download Now',
    'paymentSuccess.downloadedTimes': 'Downloaded {count} time(s)',
    'paymentSuccess.lastDownloaded': 'Last downloaded',
    'paymentSuccess.accessDownloads': 'You can access your downloads anytime from your',
    'paymentSuccess.buyerDashboard': 'buyer dashboard',
    'paymentSuccess.orderNotFound': 'Order Not Found',
    'paymentSuccess.orderNotFoundDesc': "We couldn't find the order you're looking for.",
    'paymentSuccess.tryAgain': 'Try Again',

    // Seller Dashboard
    'seller.dashboard': 'Seller Dashboard',
    'seller.manageProducts': 'Manage your products and track your sales',
    'seller.noLimits': '✨ No limits - upload unlimited products!',
    'seller.customOrder': 'Custom Order',
    'seller.addProduct': 'Add Product',
    'seller.totalSales': 'Total Sales',
    'seller.ordersCompleted': 'Orders completed',
    'seller.products': 'Products',
    'seller.activeListings': 'Active listings',
    'seller.revenueUSD': 'Revenue (USD)',
    'seller.revenueIDR': 'Revenue (IDR)',
    'seller.totalEarnings': 'Total earnings',
    'seller.productsTab': 'Products',
    'seller.analyticsTab': 'Analytics',
    'seller.yourProducts': 'Your Products',
    'seller.manageTrack': 'Manage and track all your digital products',
    'seller.loadingProducts': 'Loading products...',
    'seller.noProductsYet': 'No products yet',
    'seller.startBusiness': 'Start your digital business by adding your first product. You can upload as many as you want - there are no limits!',
    'seller.addFirstProduct': 'Add Your First Product',
    'seller.product': 'Product',
    'seller.category': 'Category',
    'seller.priceUSD': 'Price (USD)',
    'seller.priceIDR': 'Price (IDR)',
    'seller.sales': 'Sales',
    'seller.status': 'Status',
    'seller.actions': 'Actions',
    'seller.browse': 'Browse',
    'seller.logout': 'Logout',
    'seller.accountLimited': 'Account Limited',
    'seller.accountLimitedDesc': 'Your seller account has been limited due to receiving a low rating from a buyer. Your products are still visible, but buyers will see a warning on your seller page.',
    'seller.contactAdmin': 'Contact admin to resolve this issue',
    'seller.deleteProduct': 'Delete Product',
    'seller.deleteConfirm': 'Are you sure you want to delete this product? This action cannot be undone.',
    'seller.cancel': 'Cancel',
    'seller.delete': 'Delete',
    'seller.settings': 'Settings',

    // Seller Settings Page
    'sellerSettings.title': 'Seller Settings',
    'sellerSettings.description': 'Customize your shop profile and appearance',
    'sellerSettings.backToDashboard': 'Back to Dashboard',
    'sellerSettings.shopAvatar': 'Shop Avatar',
    'sellerSettings.avatarHint': 'Recommended: 200x200px, PNG or JPG, max 2MB',
    'sellerSettings.uploadAvatar': 'Upload Avatar',
    'sellerSettings.shopName': 'Shop Name',
    'sellerSettings.shopNamePlaceholder': 'Enter your shop name',
    'sellerSettings.shopDescription': 'Shop Description',
    'sellerSettings.shopDescriptionPlaceholder': 'Tell buyers about your shop and what you sell...',
    'sellerSettings.characters': 'characters',
    'sellerSettings.saveChanges': 'Save Changes',
    'sellerSettings.saveSuccess': 'Profile updated successfully!',
    'sellerSettings.saveError': 'Failed to update profile. Please try again.',
    'sellerSettings.invalidFileType': 'Only PNG and JPG files are allowed',
    'sellerSettings.fileTooLarge': 'File size must be less than 2MB',

    // Buyer Dashboard
    'buyer.dashboard': 'My Dashboard',
    'buyer.managePurchases': 'Manage your purchases and view order history',
    'buyer.myPurchases': 'My Purchases',
    'buyer.orderHistory': 'Order History',
    'buyer.downloaded': 'Downloaded',
    'buyer.times': 'times',
    'buyer.last': 'Last',
    'buyer.leaveReview': 'Leave Review',
    'buyer.reviewed': 'Reviewed',
    'buyer.download': 'Download',
    'buyer.noPurchases': 'No purchases yet',
    'buyer.startExploring': 'Start exploring our marketplace to find amazing digital products',
    'buyer.noOrders': 'No orders yet',
    'buyer.orderHistoryDesc': 'Your order history will appear here once you make a purchase',
    'buyer.date': 'Date',
    'buyer.amount': 'Amount',
    'buyer.action': 'Action',
    'buyer.payNow': 'Pay Now',
    'buyer.viewProduct': 'View Product',
    'buyer.leaveReviewFor': 'Leave a Review for',

    // Chat Page
    'chat.messages': 'Messages',
    'chat.chatWithBuyersSellers': 'Chat with buyers and sellers',
    'chat.conversations': 'Conversations',
    'chat.loading': 'Loading...',
    'chat.noConversations': 'No conversations yet',
    'chat.startFromProduct': 'Start a chat from a product page',
    'chat.selectConversation': 'Select a conversation',
    'chat.chooseConversation': 'Choose a conversation from the list to start chatting',
    'chat.typeMessage': 'Type a message...',
  },
  id: {
    // Navigation
    'nav.products': 'Produk',
    'nav.admin': 'Admin',
    'nav.messages': 'Pesan',
    'nav.login': 'Masuk',
    'nav.startSelling': 'Mulai Jual',
    'nav.dashboard': 'Dasbor',
    'nav.sellerDashboard': 'Dasbor Penjual',
    'nav.buyerDashboard': 'Dasbor Pembeli',
    'nav.signOut': 'Keluar',
    
    // Hero Section
    'hero.badge': 'Marketplace Digital Global',
    'hero.title': 'Jual & Beli Produk Digital Dengan Mudah',
    'hero.subtitle': 'Platform global untuk kreator menjual e-book, desain, musik, perangkat lunak, template, dan banyak lagi.',
    'hero.startSelling': 'Mulai Jual Sekarang',
    'hero.viewProducts': 'Lihat Produk',
    
    // How It Works
    'howItWorks.title': 'Cara Kerja',
    'howItWorks.subtitle': 'Mulai jual dalam 4 langkah mudah',
    'howItWorks.step1.title': 'Buat Akun',
    'howItWorks.step1.desc': 'Daftar gratis',
    'howItWorks.step2.title': 'Unggah Produk',
    'howItWorks.step2.desc': 'Tambah file atau link',
    'howItWorks.step3.title': 'Terima Pembayaran',
    'howItWorks.step3.desc': 'Pembayaran aman',
    'howItWorks.step4.title': 'Pembeli Unduh',
    'howItWorks.step4.desc': 'Akses instan',
    
    // Advantages
    'advantages.title': 'Keunggulan Digisellix',
    'advantages.subtitle': 'Marketplace terpercaya untuk kreator',
    'advantages.payments.title': 'Pembayaran Cepat',
    'advantages.payments.desc': 'Pembayaran global aman',
    'advantages.global.title': 'Penjual Global',
    'advantages.global.desc': 'Jangkauan seluruh dunia',
    'advantages.upload.title': 'Unggah Fleksibel',
    'advantages.upload.desc': 'File atau link',
    'advantages.platform.title': 'Platform Modern',
    'advantages.platform.desc': 'Mudah digunakan',
    
    // Product Sections
    'featured.badge': 'Produk Unggulan',
    'featured.title': 'Pilihan Premium',
    'featured.subtitle': 'Produk premium pilihan dari kreator terbaik',
    'popular.badge': 'Terlaris',
    'popular.title': 'Produk Populer',
    'popular.subtitle': 'Produk paling banyak dibeli oleh komunitas kami',
    'popularSellers.badge': 'Penjual Terbaik Bulan Ini',
    'popularSellers.title': 'Penjual Populer',
    'popularSellers.subtitle': 'Penjual dengan penjualan terbanyak bulan ini',
    'popularSellers.noDescription': 'Penjual produk digital berkualitas',
    'popularSellers.sales': 'penjualan',
    'popularSellers.products': 'produk',
    'popularSellers.viewStore': 'Lihat Toko',
    'newest.badge': 'Baru Ditambahkan',
    'newest.title': 'Produk Terbaru',
    'newest.subtitle': 'Produk baru yang ditambahkan ke marketplace',
    'reviews.badge': 'Ulasan Pelanggan',
    'reviews.title': 'Kata Pembeli',
    'reviews.subtitle': 'Ulasan terbaru dari pelanggan puas kami',
    'reviews.noComment': 'Produk bagus!',
    'explore.title': 'Jelajahi Semua Produk',
    'explore.subtitle': 'Telusuri koleksi lengkap produk digital kami',
    'explore.viewAll': 'Lihat Semua Produk',
    
    // CTA
    'cta.title': 'Siap Memulai Bisnis Digital Anda?',
    'cta.subtitle': 'Bergabung dengan ribuan kreator yang mempercayai Digisellix',
    'cta.button': 'Mulai Gratis Sekarang',
    
    // Footer
    'footer.tagline': 'Marketplace global untuk produk digital',
    'footer.product': 'Produk',
    'footer.browseProducts': 'Jelajahi Produk',
    'footer.sellProducts': 'Jual Produk',
    'footer.company': 'Perusahaan',
    'footer.about': 'Tentang',
    'footer.contact': 'Kontak',
    'footer.contactAdmin': 'Hubungi Admin',
    'footer.legal': 'Legal',
    'footer.terms': 'Syarat',
    'footer.privacy': 'Privasi',
    'footer.copyright': '© 2024 Digisellix. Hak cipta dilindungi.',
    'footer.notification': 'Selamat datang di Digisellix - Marketplace digital terpercaya!',
    'footer.notificationSales': 'Produk baru ditambahkan setiap hari',
    'footer.notificationTrust': 'Pembayaran aman & unduhan instan',
    
    // Products Page
    'products.title': 'Temukan Produk',
    'products.subtitle': 'Temukan produk digital yang sempurna untuk kebutuhan Anda',
    'products.allCategories': 'Semua Kategori',
    'products.searchPlaceholder': 'Cari produk...',
    'products.priceRange': 'Rentang Harga',
    'products.noProducts': 'Tidak ada produk ditemukan',
    'products.tryAdjusting': 'Coba sesuaikan pencarian atau filter Anda',
    'products.previous': 'Sebelumnya',
    'products.next': 'Selanjutnya',
    
    // Product Card
    'product.viewDetails': 'Lihat Detail',
    'product.topRated': 'Top',
    'product.reviews': 'ulasan',
    
    // Wishlist
    'wishlist.title': 'Wishlist Saya',
    'wishlist.subtitle': 'Produk yang disimpan untuk nanti',
    'wishlist.empty': 'Wishlist Anda kosong',
    'wishlist.emptyDesc': 'Mulai tambahkan produk favorit ke wishlist Anda',
    'wishlist.browseProducts': 'Jelajahi Produk',
    'nav.wishlist': 'Wishlist',
    
    // Blog
    'blog.title': 'Blog Digisellix',
    'blog.subtitle': 'Tips, panduan, dan sumber daya untuk kreator dan penjual digital',
    'nav.blog': 'Blog',

    // Contact Page
    'contact.title': 'Hubungi Kami',
    'contact.subtitle': 'Punya pertanyaan? Kami siap membantu. Hubungi tim kami.',
    'contact.emailTitle': 'Email',
    'contact.chatTitle': 'Live Chat',
    'contact.chatDesc': 'Chat dengan tim support kami via WhatsApp',
    'contact.hoursTitle': 'Jam Kerja',
    'contact.hoursDesc': 'Senin - Jumat, 09.00 - 18.00 (WIB)',
    'contact.locationTitle': 'Lokasi',
    'contact.locationDesc': 'Jakarta, Indonesia',
    'contact.formTitle': 'Kirim Pesan',
    'contact.formDesc': 'Isi formulir di bawah dan kami akan segera menghubungi Anda.',
    'contact.nameLabel': 'Nama',
    'contact.namePlaceholder': 'Nama Anda',
    'contact.emailLabel': 'Email',
    'contact.emailPlaceholder': 'email@anda.com',
    'contact.subjectLabel': 'Subjek',
    'contact.subjectPlaceholder': 'Tentang apa?',
    'contact.messageLabel': 'Pesan',
    'contact.messagePlaceholder': 'Beritahu kami bagaimana kami bisa membantu...',
    'contact.sendButton': 'Kirim Pesan',
    'contact.sending': 'Mengirim...',
    'contact.successTitle': 'Pesan Terkirim!',
    'contact.successMessage': 'Terima kasih telah menghubungi kami. Kami akan segera membalas.',
    'contact.errorTitle': 'Error',
    'contact.errorMessage': 'Gagal mengirim pesan. Silakan coba lagi.',
    
    // Language Switcher
    'language.english': 'English',
    'language.indonesian': 'Indonesia',

    // Auth Page
    'auth.login': 'Masuk',
    'auth.signup': 'Daftar',
    'auth.welcomeBack': 'Selamat Datang Kembali',
    'auth.enterCredentials': 'Masukkan kredensial Anda untuk mengakses akun',
    'auth.createAccount': 'Buat Akun',
    'auth.startSelling': 'Mulai jual produk digital Anda hari ini',
    'auth.email': 'Email',
    'auth.password': 'Kata Sandi',
    'auth.fullName': 'Nama Lengkap',
    'auth.loading': 'Memuat...',
    'auth.iWantTo': 'Saya ingin',
    'auth.buyProducts': 'Beli Produk',
    'auth.buyProductsDesc': 'Beli dan unduh produk digital',
    'auth.sellProducts': 'Jual Produk',
    'auth.sellProductsDesc': 'Unggah dan jual produk digital Anda',
    'auth.selectBoth': 'Anda dapat memilih kedua opsi untuk membeli dan menjual',
    'auth.orContinueWith': 'Atau lanjutkan dengan',
    'auth.googleLoginFailed': 'Login Google gagal',
    'auth.redirectingToGoogle': 'Mengalihkan ke Google...',
    'auth.backToHome': '← Kembali ke Beranda',

    // Product Detail Page
    'productDetail.backToProducts': 'Kembali ke Produk',
    'productDetail.by': 'Oleh',
    'productDetail.sales': 'penjualan',
    'productDetail.securePurchase': 'Pembelian Aman',
    'productDetail.instantAccess': 'Akses instan setelah pembayaran. Semua file dipindai dan diverifikasi.',
    'productDetail.buyNow': 'Beli Sekarang',
    'productDetail.chatWithSeller': 'Chat dengan Penjual',
    'productDetail.starting': 'Memulai...',
    'productDetail.description': 'Deskripsi',
    'productDetail.productDetails': 'Detail Produk',
    'productDetail.category': 'Kategori',
    'productDetail.totalSales': 'Total Penjualan',
    'productDetail.listedOn': 'Terdaftar pada',
    'productDetail.relatedProducts': 'Produk Terkait',
    'productDetail.notFound': 'Produk tidak ditemukan',
    'productDetail.notFoundDesc': 'Produk yang Anda cari tidak ada atau telah dihapus.',
    'productDetail.pleaseSignIn': 'Silakan masuk untuk membeli',
    'productDetail.cannotBuyOwn': 'Anda tidak dapat membeli produk sendiri',
    'productDetail.orderCreated': 'Pesanan dibuat! Mengalihkan ke checkout...',
    'productDetail.pleaseSignInChat': 'Silakan masuk untuk chat dengan penjual',
    'productDetail.ownProduct': 'Ini adalah produk Anda sendiri',
    'productDetail.faq': 'Pertanyaan yang Sering Diajukan',

    // Share
    'share.title': 'Bagikan',
    'share.shareVia': 'Bagikan via',
    'share.copyLink': 'Salin tautan',
    'share.copied': 'Tersalin!',
    'share.linkCopied': 'Tautan disalin ke clipboard',
    'share.copyFailed': 'Gagal menyalin tautan',
    'share.more': 'Opsi lainnya',

    // Forum
    'nav.forum': 'Forum',
    'forum.title': 'Forum Komunitas',
    'forum.subtitle': 'Diskusi dengan komunitas',
    'forum.newTopic': 'Topik Baru',
    'forum.comments': 'komentar',
    'forum.noTopics': 'Belum ada topik',
    'forum.beFirst': 'Jadilah yang pertama memulai diskusi!',
    'forum.createTopic': 'Buat Topik',
    'forum.signInToPost': 'Masuk untuk posting',
    'forum.joinDiscussion': 'Ingin bergabung dalam diskusi?',
    'forum.backToForum': 'Kembali ke Forum',
    'forum.topicNotFound': 'Topik tidak ditemukan',
    'forum.noComments': 'Belum ada komentar. Jadilah yang pertama berkomentar!',
    'forum.writeComment': 'Tulis komentar...',
    'forum.postComment': 'Kirim Komentar',
    'forum.posting': 'Mengirim...',
    'forum.commentAdded': 'Komentar ditambahkan!',
    'forum.commentError': 'Gagal menambahkan komentar',
    'forum.commentDeleted': 'Komentar dihapus',
    'forum.signInToComment': 'Masuk untuk berkomentar',
    'forum.createNewTopic': 'Buat Topik Baru',
    'forum.moderationNotice': 'Topik Anda akan ditinjau oleh tim kami sebelum dipublikasikan.',
    'forum.topicTitle': 'Judul Topik',
    'forum.titlePlaceholder': 'Masukkan judul yang deskriptif...',
    'forum.topicContent': 'Konten',
    'forum.contentPlaceholder': 'Bagikan pemikiran, pertanyaan, atau ide Anda...',
    'forum.cancel': 'Batal',
    'forum.submitTopic': 'Kirim Topik',
    'forum.submitting': 'Mengirim...',
    'forum.topicSubmitted': 'Topik dikirim untuk ditinjau!',
    'forum.submitError': 'Gagal mengirim topik',
    'forum.fillAllFields': 'Harap isi semua kolom',
    'forum.signInRequired': 'Harus masuk',
    'forum.signInToCreateTopic': 'Silakan masuk untuk membuat topik baru.',
    'forum.pendingReview': 'Menunggu Tinjauan',
    'forum.allTopics': 'Semua Topik',
    'forum.approved': 'Disetujui',
    'forum.rejected': 'Ditolak',
    'forum.pending': 'Menunggu',
    'forum.topicApproved': 'Topik disetujui!',
    'forum.topicRejected': 'Topik ditolak',
    'forum.topicDeleted': 'Topik dihapus',
    'forum.updateError': 'Gagal memperbarui topik',
    'forum.confirmDelete': 'Hapus Topik?',
    'forum.deleteWarning': 'Tindakan ini tidak dapat dibatalkan. Topik dan semua komentarnya akan dihapus secara permanen.',
    'forum.delete': 'Hapus',
    'forum.noPendingTopics': 'Tidak ada topik yang menunggu tinjauan',
    'forum.noTopicsYet': 'Belum ada topik yang dibuat',

    // Checkout Page
    'checkout.title': 'Checkout',
    'checkout.back': 'Kembali',
    'checkout.orderSummary': 'Ringkasan Pesanan',
    'checkout.customOrder': 'Pesanan Khusus',
    'checkout.digitalProduct': 'Produk Digital',
    'checkout.priceUSD': 'Harga (USD)',
    'checkout.priceIDR': 'Harga (IDR)',
    'checkout.total': 'Total',
    'checkout.paymentMethod': 'Metode Pembayaran',
    'checkout.securePayment': 'Pemrosesan pembayaran aman oleh PayPal',
    'checkout.paypalOptions': 'Opsi Pembayaran PayPal:',
    'checkout.paypalBalance': 'Saldo PayPal',
    'checkout.creditDebit': 'Kartu Kredit/Debit (Visa, Mastercard, Amex)',
    'checkout.bankAccounts': 'Rekening Bank (terhubung ke PayPal)',
    'checkout.continuePaypal': 'Lanjutkan dengan PayPal',
    'checkout.secureInfo': 'Informasi pembayaran Anda dienkripsi dan aman. Anda akan mendapatkan akses instan ke pembelian setelah pembayaran dikonfirmasi.',
    'checkout.orderNotFound': 'Pesanan tidak ditemukan',
    'checkout.browseProducts': 'Jelajahi Produk',
    'checkout.creatingPayment': 'Membuat pembayaran...',
    'checkout.redirectingPaypal': 'Mengalihkan ke PayPal...',
    'checkout.pleaseSignIn': 'Silakan masuk untuk melanjutkan',

    // Payment Success Page
    'paymentSuccess.backToDashboard': 'Kembali ke Dasbor',
    'paymentSuccess.paymentSuccessful': 'Pembayaran Berhasil!',
    'paymentSuccess.orderConfirmed': 'Pesanan Anda telah dikonfirmasi dan siap untuk diunduh.',
    'paymentSuccess.paid': 'Dibayar',
    'paymentSuccess.paymentPending': 'Pembayaran Tertunda',
    'paymentSuccess.waitingConfirmation': 'Kami menunggu konfirmasi pembayaran. Halaman ini akan diperbarui secara otomatis.',
    'paymentSuccess.pending': 'Tertunda',
    'paymentSuccess.paymentFailed': 'Pembayaran Gagal',
    'paymentSuccess.couldNotProcess': 'Pembayaran Anda tidak dapat diproses. Silakan coba lagi.',
    'paymentSuccess.failed': 'Gagal',
    'paymentSuccess.orderDetails': 'Detail Pesanan',
    'paymentSuccess.orderId': 'ID Pesanan',
    'paymentSuccess.paymentMethod': 'Metode Pembayaran',
    'paymentSuccess.amount': 'Jumlah',
    'paymentSuccess.paidAt': 'Dibayar Pada',
    'paymentSuccess.downloadProduct': 'Unduh Produk Anda',
    'paymentSuccess.purchaseReady': 'Pembelian Anda siap! Klik tombol di bawah untuk mengunduh produk digital Anda.',
    'paymentSuccess.downloadNow': 'Unduh Sekarang',
    'paymentSuccess.downloadedTimes': 'Diunduh {count} kali',
    'paymentSuccess.lastDownloaded': 'Terakhir diunduh',
    'paymentSuccess.accessDownloads': 'Anda dapat mengakses unduhan kapan saja dari',
    'paymentSuccess.buyerDashboard': 'dasbor pembeli',
    'paymentSuccess.orderNotFound': 'Pesanan Tidak Ditemukan',
    'paymentSuccess.orderNotFoundDesc': 'Kami tidak dapat menemukan pesanan yang Anda cari.',
    'paymentSuccess.tryAgain': 'Coba Lagi',

    // Seller Dashboard
    'seller.dashboard': 'Dasbor Penjual',
    'seller.manageProducts': 'Kelola produk dan lacak penjualan Anda',
    'seller.noLimits': '✨ Tanpa batas - unggah produk tanpa batas!',
    'seller.customOrder': 'Pesanan Khusus',
    'seller.addProduct': 'Tambah Produk',
    'seller.totalSales': 'Total Penjualan',
    'seller.ordersCompleted': 'Pesanan selesai',
    'seller.products': 'Produk',
    'seller.activeListings': 'Listing aktif',
    'seller.revenueUSD': 'Pendapatan (USD)',
    'seller.revenueIDR': 'Pendapatan (IDR)',
    'seller.totalEarnings': 'Total pendapatan',
    'seller.productsTab': 'Produk',
    'seller.analyticsTab': 'Analitik',
    'seller.yourProducts': 'Produk Anda',
    'seller.manageTrack': 'Kelola dan lacak semua produk digital Anda',
    'seller.loadingProducts': 'Memuat produk...',
    'seller.noProductsYet': 'Belum ada produk',
    'seller.startBusiness': 'Mulai bisnis digital Anda dengan menambahkan produk pertama. Anda dapat mengunggah sebanyak yang Anda mau - tidak ada batasan!',
    'seller.addFirstProduct': 'Tambah Produk Pertama Anda',
    'seller.product': 'Produk',
    'seller.category': 'Kategori',
    'seller.priceUSD': 'Harga (USD)',
    'seller.priceIDR': 'Harga (IDR)',
    'seller.sales': 'Penjualan',
    'seller.status': 'Status',
    'seller.actions': 'Aksi',
    'seller.browse': 'Jelajahi',
    'seller.logout': 'Keluar',
    'seller.accountLimited': 'Akun Dibatasi',
    'seller.accountLimitedDesc': 'Akun penjual Anda telah dibatasi karena menerima rating rendah dari pembeli. Produk Anda masih terlihat, tetapi pembeli akan melihat peringatan di halaman penjual Anda.',
    'seller.contactAdmin': 'Hubungi admin untuk menyelesaikan masalah ini',
    'seller.deleteProduct': 'Hapus Produk',
    'seller.deleteConfirm': 'Apakah Anda yakin ingin menghapus produk ini? Tindakan ini tidak dapat dibatalkan.',
    'seller.cancel': 'Batal',
    'seller.delete': 'Hapus',
    'seller.settings': 'Pengaturan',

    // Seller Settings Page
    'sellerSettings.title': 'Pengaturan Penjual',
    'sellerSettings.description': 'Sesuaikan profil dan tampilan toko Anda',
    'sellerSettings.backToDashboard': 'Kembali ke Dasbor',
    'sellerSettings.shopAvatar': 'Avatar Toko',
    'sellerSettings.avatarHint': 'Disarankan: 200x200px, PNG atau JPG, maks 2MB',
    'sellerSettings.uploadAvatar': 'Unggah Avatar',
    'sellerSettings.shopName': 'Nama Toko',
    'sellerSettings.shopNamePlaceholder': 'Masukkan nama toko Anda',
    'sellerSettings.shopDescription': 'Deskripsi Toko',
    'sellerSettings.shopDescriptionPlaceholder': 'Ceritakan kepada pembeli tentang toko Anda dan apa yang Anda jual...',
    'sellerSettings.characters': 'karakter',
    'sellerSettings.saveChanges': 'Simpan Perubahan',
    'sellerSettings.saveSuccess': 'Profil berhasil diperbarui!',
    'sellerSettings.saveError': 'Gagal memperbarui profil. Silakan coba lagi.',
    'sellerSettings.invalidFileType': 'Hanya file PNG dan JPG yang diperbolehkan',
    'sellerSettings.fileTooLarge': 'Ukuran file harus kurang dari 2MB',

    // Buyer Dashboard
    'buyer.dashboard': 'Dasbor Saya',
    'buyer.managePurchases': 'Kelola pembelian dan lihat riwayat pesanan',
    'buyer.myPurchases': 'Pembelian Saya',
    'buyer.orderHistory': 'Riwayat Pesanan',
    'buyer.downloaded': 'Diunduh',
    'buyer.times': 'kali',
    'buyer.last': 'Terakhir',
    'buyer.leaveReview': 'Beri Ulasan',
    'buyer.reviewed': 'Sudah Diulas',
    'buyer.download': 'Unduh',
    'buyer.noPurchases': 'Belum ada pembelian',
    'buyer.startExploring': 'Mulai jelajahi marketplace kami untuk menemukan produk digital yang menakjubkan',
    'buyer.noOrders': 'Belum ada pesanan',
    'buyer.orderHistoryDesc': 'Riwayat pesanan Anda akan muncul di sini setelah Anda melakukan pembelian',
    'buyer.date': 'Tanggal',
    'buyer.amount': 'Jumlah',
    'buyer.action': 'Aksi',
    'buyer.payNow': 'Bayar Sekarang',
    'buyer.viewProduct': 'Lihat Produk',
    'buyer.leaveReviewFor': 'Beri Ulasan untuk',

    // Chat Page
    'chat.messages': 'Pesan',
    'chat.chatWithBuyersSellers': 'Chat dengan pembeli dan penjual',
    'chat.conversations': 'Percakapan',
    'chat.loading': 'Memuat...',
    'chat.noConversations': 'Belum ada percakapan',
    'chat.startFromProduct': 'Mulai chat dari halaman produk',
    'chat.selectConversation': 'Pilih percakapan',
    'chat.chooseConversation': 'Pilih percakapan dari daftar untuk mulai mengobrol',
    'chat.typeMessage': 'Ketik pesan...',
  },
};

// Detect Indonesian IP
async function detectIndonesianIP(): Promise<boolean> {
  try {
    const response = await fetch('https://ipapi.co/json/');
    const data = await response.json();
    return data.country_code === 'ID';
  } catch (error) {
    console.error('Failed to detect IP location:', error);
    return false;
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check localStorage first
    const saved = localStorage.getItem('digisellix-language');
    if (saved === 'en' || saved === 'id') return saved;
    return 'en'; // Default to English
  });
  const [initialized, setInitialized] = useState(false);

  useEffect(() => {
    // Only auto-detect if no saved preference
    const saved = localStorage.getItem('digisellix-language');
    if (!saved && !initialized) {
      detectIndonesianIP().then((isIndonesian) => {
        if (isIndonesian) {
          setLanguageState('id');
          localStorage.setItem('digisellix-language', 'id');
        }
        setInitialized(true);
      });
    } else {
      setInitialized(true);
    }
  }, [initialized]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('digisellix-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Fallback to a safe default to avoid runtime crashes if the provider
    // is temporarily missing in some render tree (e.g. during HMR).
    return {
      language: 'en' as Language,
      setLanguage: () => {},
      t: (key: string) => translations.en[key] || key,
    } satisfies LanguageContextType;
  }
  return context;
}

